### ISSUE TITLE
V1 & V2 Alpha - CopyStationsFromLocoToCoaches - Unreliable & Edge case midroute

### ISSUE THREAD

**Issue by GamearooCodes** [Erabior/RouteManager#54]
after i added up to 12 cars it failed to paste the stations to the train cars and no passangers get picked up this can be a issue as the whole point is to pick up the passangers not leave them behind

**Comment by Narflar** [comment]
i ran into this issue today as well.  I have 4 cars and added 2 new stations and they weren't being added to the passenger cars.  The train was stopping at the stations but nothing was selected in the passenger cars.  After I manually selected all the stations in the passenger cars did it start to work properly.

**Comment by AdamC1228** [comment]
This should be addressed with the 2.0 version but for my sanity, please provide the logs so I can see if there is an unaccounted for edge case.

**Comment by GamearooCodes** [comment]
> This should be addressed with the 2.0 version but for my sanity, please provide the logs so I can see if there is an unaccounted for edge case.

here is the full log from that session 

[Player-prev.log](https://github.com/Erabior/RouteManager/files/13825311/Player-prev.log)

**Comment by AdamC1228** [comment]
Thank you, I will review it but in the mean time you will find an alpha pre-release for V2.0. Please retry with the alpha and report any improvement, if at all.

**Comment by GamearooCodes** [comment]
the 2.0 version still isnt selecting the stations at least for where its heading rn its heading to bryson area and east whitterer and ela it didnt stopm for wilmont disboro or sylva depot 
![image](https://github.com/Erabior/RouteManager/assets/50187502/4000f878-3b44-42a3-9379-b899b994f2be)

**Comment by GamearooCodes** [comment]
![image](https://github.com/Erabior/RouteManager/assets/50187502/7613f865-8560-4e12-96fd-1077db47e932)
i do have it seup correctly idk why but it doesnt seem to work with the max speed selector

**Comment by GamearooCodes** [comment]
[Player.log](https://github.com/Erabior/RouteManager/files/13830546/Player.log)
new log file the new alpha for 2.0 is completly broken for me it doesnt stop at any station at all minus being told to do so

**Comment by GamearooCodes** [comment]
yeah just bypassed all stations and went to a dead end im going to have to backtrack mod to old version as at least it worked after you added the stations to the passanger coaches

![image](https://github.com/Erabior/RouteManager/assets/50187502/fb81bf6b-fb33-464b-93f4-ff6a71fc74e6)

if i had to guess its the games ai taking over bc we selected a max speed maybe make this a config option in the .ini instead and make it do it the way it did b4 except using the max speed in the ini tells it how fast it can go if the track speed doesnt say otherwise

**Comment by GamearooCodes** [comment]
after going back to the latest 1.x version i can confirm its a issue in 2.0 itself now ofc ill have to add teh stations to the coaches manully for loading passangers  which was sad bc i was looking fowrd to the new station passanger looking thing to get all passangers :(

**Comment by AdamC1228** [comment]
Thanks for the feed back. The issue with speed control is a regression that slipped in with the last pull request that will be addressed in Alpha 2. As for the station selection I have identified an edge case that can be improved that I think will solve this. Additionally the new code may be exposing a bug with the game itself independent of the mod which was not exposed in internal testing. I have reached out to the developers 

Thanks for testing to confirm if the upcoming V2 fared any better.

**Comment by GamearooCodes** [comment]
> Thanks for the feed back. The issue with speed control is a regression that slipped in with the last pull request that will be addressed in Alpha 2. As for the station selection I have identified an edge case that can be improved that I think will solve this. Additionally the new code may be exposing a bug with the game itself independent of the mod which was not exposed in internal testing. I have reached out to the developers
> 
> Thanks for testing to confirm if the upcoming V2 fared any better.

np and ill def be looking fowrd to alpha 2 wish i could help code the mod a bit but i never done a mod for a game without modding docs b4 so

**Comment by armyf35** [comment]
It looks like `LocoTelem.needToUpdatePassengerCoaches` is only set to `true` when it is at the first or last station, meaning when it starts in the middle of the route nothing gets updated.

This is in regards to Alpha 1, not sure about the stable version.

**Comment by Narflar** [comment]
That explains why i usually have to select only the next station and then add the rest once the train is under way.

**Comment by AdamC1228** [comment]
Please retest with Alpha 2 and report back on the results.

**Comment by GamearooCodes** [comment]
its stoping now but still doesnt select the stations its heading to to the coaches which is fine ig if its not fixable as we can always manully select them the first time as after it works fine

**Comment by GamearooCodes** [comment]
i stand corrected it broke and stoped stoping for stations after messing witjh the max speed knob

**Comment by GamearooCodes** [comment]
basicl alpha 2 has the same issue with the speed knob and passanger coach selection

**Comment by AdamC1228** [comment]
@GamearooCodes Can you post an updated player log and the exact steps you took?

**Comment by GamearooCodes** [comment]
i dont have the player logs the exat steps was just set up the rout turn it on and set it to max speed 30 and it bypasses the stations

**Comment by GamearooCodes** [comment]
if you like i can test it tm with my new save and report back

**Comment by AdamC1228** [comment]
@GamearooCodes Yes, please retest on your new save using the latest V2 Release.

**Comment by AdamC1228** [comment]
No feedback in 2 weeks. Marking as closed.
